services:
  web:
    build: .
    container_name: vk-killer
    env_file: .env
    depends_on:
      - db
      - redis
    volumes:
      - ./src:/app
      - ./logs:/var/log
    restart: unless-stopped
  redis:
    image: redis
    container_name: vk-killer-redis
    restart: unless-stopped
  db:
    image: postgres:14-alpine
    container_name: vk-killer-postgres
    volumes:
      - ./data-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=vkkiller
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  nginx:
    image: nginx:alpine
    container_name: vk-killer-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src/static:/usr/share/nginx/static:ro
      - ./src/media:/usr/share/nginx/media:ro
    ports:
      - "8000:80"
    depends_on:
      - web
    restart: unless-stopped
